### ISSUE TITLE
[EngAut] Auto-Merge-Bot version 1

### ISSUE THREAD

**Issue by Bullrich** [paritytech/auto-merge-bot#7]
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/auto-merge-bot/issues/1
- [ ] https://github.com/paritytech/auto-merge-bot/issues/2
- [ ] https://github.com/paritytech/auto-merge-bot/issues/3
- [ ] https://github.com/paritytech/auto-merge-bot/issues/4
- [ ] https://github.com/paritytech/auto-merge-bot/issues/6
- [ ] https://github.com/paritytech/auto-merge-bot/issues/8
- [ ] https://github.com/paritytech/auto-merge-bot/issues/12
```
This issue is required for https://github.com/polkadot-fellows/runtimes/issues/41

Related task: https://github.com/paritytech/get-fellows-action/issues/3

Milestone containing all the changes: [Version 1.0.0](https://github.com/paritytech/auto-merge-bot/milestone/1)
